[ipfs]
    # The address of the API server for your IPFS node.
    api = "http://127.0.0.1:5001"

    # Generate URLs using a public gateway. If this is false, ipfs:// URLs will
    # be generated instead.
    use-gateway = true

    # The public gateway to use for generating URLs.
    gateway = "dweb.link"

    # The CAR version to use. Supported values are "1" and "2".
    car-version = "1"

[archive]
    # A golang `text/template` template which is passed the contents of the
    # bibtex entry and returns the name of the source directory. Functions
    # provided by the sprig library are available in the template. The
    # following field are available in the template:
    # .Key - The bibtex entry ID
    # .Type - The bibtex entry type (e.g. "article")
    # .Fields - A map of fields that appear in the bibtex entry
    name-template = "{{ coalesce (get .Fields \"doi\") .Key }}"

    # The media types (MIME types) of content that the tool will not attempt to
    # archive.
    #excluded-types = [
    #    "text/html",
    #]

# A handler which looks for embedded documents in HTML documents.
[handler.embed]
    # Enable this handler.
    enabled = true

    # The media types (MIME types) of the embedded content to look for.
    media-types = [
        "application/pdf",
    ]

# A handler which takes a snapshot of an HTML document using monolith.
[handler.monolith]
    # Enable this handler.
    enabled = true

    # The path to the monolith binary.
    path = "monolith"


# A list of proxy rules which can be used to resolve source URLs or DOIs.
#[[proxies]]
    # A list of proxy schemes to try in order. Each scheme is a golang
    # `text/template` template which returns the proxied URL. Functions
    # provided by the sprig library are available in the template. The
    # following field are available in the template:
    # .Doi - The DOI of the entry, excluding the doi: or https://doi.org/ prefix (e.g. 10.1038/nphys1170)
    # .Hostname - The hostname of source URL (e.g. example.com)
    # .Path - The path of the source URL, excluding the leading slash (e.g. about/index.html)
    #schemes = [
    #    "example.com/{{ .Doi }}",
    #    "{{ .Hostname }}.example.com/{{ .Path }}",
    #]

    # Use this proxy rule for entries with a DOI. This supersedes `hostnames`.
    #doi = true

    # This proxy rule is only applied when the entry has a URL with one of
    # these hostnames. If this list is empty, then the proxy rule applies to
    # all entries.
    #hostnames = [
    #    "example.org",
    #    "research.example.com",
    #]
