[ipfs]
    # The address of the API server for your IPFS node.
    api = "http://127.0.0.1:5001"

    # Generate URLs using a public gateway. If this is false, ipfs:// URLs will
    # be generated instead.
    use-gateway = true

    # The public gateway to use for generating URLs.
    gateway = "dweb.link"

    # The CAR version to use. Supported values are "1" and "2".
    car-version = "1"

[archive]
    # A list of patterns to use to generate the directory names for each source
    # in IPFS. If one pattern fails because the necessary information isn't
    # available in the bibtex entry, the next pattern is used.
    # %d - The DOI of the entry
    # %t - The title of the entry
    # %y - The year of publication
    # %a - The authors of the entry
    # %i - The bibtex entry ID
    # %% - A literal %
    #name-patterns = [
    #    "%d",
    #    "%i",
    #]

    # A command which accepts a bibtex entry as stdin and writes the directory
    # name for the source to stdout. This option supersedes `name-patterns`.
    #name-command = "file-name.sh"

    # The media types (MIME types) of content that the tool will not attempt to
    # archive.
    #excluded-types = [
    #    "text/html",
    #]

# A handler which looks for embedded documents in HTML documents.
[handler.embed]
    # Enable this handler.
    enabled = true

    # The media types (MIME types) of the embedded content to look for.
    media-types = [
        "application/pdf",
    ]

# A handler which takes a snapshot of an HTML document using monolith.
[handler.monolith]
    # Enable this handler.
    enabled = true

    # The path to the monolith binary.
    path = "monolith"


# A list of proxy rules which can be used to resolve source URLs or DOIs.
#[[proxies]]
    # A list of proxy schemes to try in order. Each scheme is a URL which
    # accepts the following variables:
    # %d - The DOI of the entry, excluding the doi: or https://doi.org/ prefix (e.g. 10.1038/nphys1170)
    # %h - The hostname of source URL (e.g. example.com)
    # %p - The path of the source URL, excluding the leading slash (e.g. about/index.html)
    # %% - A literal %
    #schemes = [
    #    "example.com/%d",
    #    "%h.example.com/%p",
    #]

    # Use this proxy rule for entries with a DOI. This supersedes `hostnames`.
    #doi = true

    # This proxy rule is only applied when the entry has a URL with one of
    # these hostnames. If this list is empty, then the proxy rule applies to
    # all entries.
    #hostnames = [
    #    "example.org",
    #    "research.example.com",
    #]
